// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Location is the predicate function for location builders.
type Location func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
